#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════
#  token-audit.sh
#
#  Snapshot current extension states, enable everything for token
#  measurement, then restore when done.
#
#  Usage:
#    bash token-audit.sh --save     # snapshot state + enable everything
#    bash token-audit.sh --restore  # restore from snapshot
#
#  Workflow:
#    1. bash token-audit.sh --save
#    2. Open Claude Code and run /reload-plugins
#    3. Run /context — note each skill/plugin's token count
#    4. bash token-audit.sh --restore
#    5. Open Claude Code and run /reload-plugins to go back to normal
# ════════════════════════════════════════════════════════════════

set -euo pipefail

SETTINGS="${HOME}/.claude/settings.json"
SKILLS_DIR="${HOME}/.claude/skills"
STATE_FILE="${PWD}/token-audit-state.json"

G='\033[0;32m' Y='\033[1;33m' C='\033[0;36m' R='\033[0;31m' RESET='\033[0m'
ok()   { echo -e "${G}[done]${RESET}  $*"; }
log()  { echo -e "${C}[info]${RESET}  $*"; }
warn() { echo -e "${Y}[warn]${RESET}  $*"; }
err()  { echo -e "${R}[error]${RESET} $*"; }

# ── SAVE ─────────────────────────────────────────────────────────
save() {
  if [ -f "${STATE_FILE}" ]; then
    warn "Snapshot already exists at ${STATE_FILE}"
    printf "  Overwrite? [y/N] "
    read -r ans
    [[ "$ans" =~ ^[Yy] ]] || { echo "Aborted."; exit 0; }
  fi

  log "Snapshotting current state to ${STATE_FILE}..."
  python3 - <<PYEOF
import json, os, glob

settings_path = "${SETTINGS}"
skills_dir = "${SKILLS_DIR}"
state_file = "${STATE_FILE}"

with open(settings_path) as f:
    settings = json.load(f)

# MCP states
mcp_states = {}
for name, cfg in settings.get("mcpServers", {}).items():
    mcp_states[name] = {"disabled": cfg.get("disabled", False)}

# Plugin states
plugin_states = {}
for name, val in settings.get("enabledPlugins", {}).items():
    plugin_states[name] = val

# Skill states
skill_states = {}
for skill_md_path in sorted(glob.glob(os.path.join(skills_dir, "*/SKILL.md"))):
    skill_name = os.path.basename(os.path.dirname(skill_md_path))
    with open(skill_md_path) as f:
        content = f.read()
    if "disable-model-invocation: true" in content:
        skill_states[skill_name] = "context-off"
    elif "disable-model-invocation: false" in content:
        skill_states[skill_name] = "context-on"
    else:
        skill_states[skill_name] = "no-flag"

state = {
    "_note": "Generated by token-audit.sh --save. Do not edit manually.",
    "mcpServers": mcp_states,
    "plugins": plugin_states,
    "skills": skill_states
}

with open(state_file, "w") as f:
    json.dump(state, f, indent=2)

print(f"  {len(mcp_states)} MCPs, {len(plugin_states)} plugins, {len(skill_states)} skills recorded")
PYEOF
  ok "State snapshot saved → ${STATE_FILE}"
  echo ""

  log "Enabling all MCP servers..."
  python3 - <<PYEOF
import json

path = "${SETTINGS}"
with open(path) as f:
    data = json.load(f)

enabled = []
for name in data.get("mcpServers", {}):
    if data["mcpServers"][name].pop("disabled", None) is not None:
        enabled.append(name)

with open(path, "w") as f:
    json.dump(data, f, indent=2)

if enabled:
    for n in enabled:
        print(f"  enabled: {n}")
else:
    print("  (all already enabled)")
PYEOF
  ok "MCP servers enabled"
  echo ""

  log "Enabling all plugins..."
  python3 - <<PYEOF
import json

path = "${SETTINGS}"
with open(path) as f:
    data = json.load(f)

enabled = []
for name in data.get("enabledPlugins", {}):
    if not data["enabledPlugins"][name]:
        data["enabledPlugins"][name] = True
        enabled.append(name)

with open(path, "w") as f:
    json.dump(data, f, indent=2)

if enabled:
    for n in enabled:
        print(f"  enabled: {n}")
else:
    print("  (all already enabled)")
PYEOF
  ok "Plugins enabled"
  echo ""

  log "Setting all skills to context-on..."
  python3 - <<PYEOF
import glob, os

skills_dir = "${SKILLS_DIR}"
enabled = []
skipped = []

for skill_md_path in sorted(glob.glob(os.path.join(skills_dir, "*/SKILL.md"))):
    skill_name = os.path.basename(os.path.dirname(skill_md_path))
    with open(skill_md_path) as f:
        content = f.read()
    if "disable-model-invocation: true" in content:
        content = content.replace("disable-model-invocation: true", "disable-model-invocation: false")
        with open(skill_md_path, "w") as f:
            f.write(content)
        enabled.append(skill_name)
    else:
        skipped.append(skill_name)

for n in enabled:
    print(f"  enabled: {n}")
if skipped:
    print(f"  already context-on: {', '.join(skipped)}")
PYEOF
  ok "All skills set to context-on"
  echo ""

  echo -e "${Y}════════════════════════════════════════════════════════════${RESET}"
  echo -e "${Y}  Next steps:${RESET}"
  echo    "  1. Open Claude Code and run: /reload-plugins"
  echo    "  2. Run /context — note the token count for each skill/plugin"
  echo    "  3. Record token counts in the HTML dashboard"
  echo    "  4. Run: bash token-audit.sh --restore"
  echo    "  5. Open Claude Code and run: /reload-plugins"
  echo -e "${Y}════════════════════════════════════════════════════════════${RESET}"
}

# ── RESTORE ──────────────────────────────────────────────────────
restore() {
  if [ ! -f "${STATE_FILE}" ]; then
    err "No snapshot found at ${STATE_FILE}. Run --save first."
    exit 1
  fi

  log "Restoring state from ${STATE_FILE}..."
  python3 - <<PYEOF
import json, glob, os

settings_path = "${SETTINGS}"
skills_dir = "${SKILLS_DIR}"
state_file = "${STATE_FILE}"

with open(state_file) as f:
    state = json.load(f)

with open(settings_path) as f:
    settings = json.load(f)

# Restore MCPs
mcp_restored = []
for name, saved in state.get("mcpServers", {}).items():
    if name not in settings.get("mcpServers", {}):
        continue
    if saved["disabled"]:
        settings["mcpServers"][name]["disabled"] = True
    else:
        settings["mcpServers"][name].pop("disabled", None)
    mcp_restored.append(name)

# Restore plugins
plugin_restored = []
for name, val in state.get("plugins", {}).items():
    if name in settings.get("enabledPlugins", {}):
        settings["enabledPlugins"][name] = val
        plugin_restored.append(name)

with open(settings_path, "w") as f:
    json.dump(settings, f, indent=2)

print(f"  {len(mcp_restored)} MCPs restored")
print(f"  {len(plugin_restored)} plugins restored")

# Restore skills
skill_restored = 0
for skill_name, saved_state in state.get("skills", {}).items():
    skill_md_path = os.path.join(skills_dir, skill_name, "SKILL.md")
    if not os.path.exists(skill_md_path):
        continue
    with open(skill_md_path) as f:
        content = f.read()
    if saved_state == "context-off" and "disable-model-invocation: false" in content:
        content = content.replace("disable-model-invocation: false", "disable-model-invocation: true")
        with open(skill_md_path, "w") as f:
            f.write(content)
        skill_restored += 1
    elif saved_state == "context-on" and "disable-model-invocation: true" in content:
        content = content.replace("disable-model-invocation: true", "disable-model-invocation: false")
        with open(skill_md_path, "w") as f:
            f.write(content)
        skill_restored += 1

print(f"  {skill_restored} skills restored")
PYEOF
  ok "State restored from ${STATE_FILE}"
  echo ""
  warn "Open Claude Code and run /reload-plugins to apply plugin and MCP changes"
}

# ── MAIN ─────────────────────────────────────────────────────────
case "${1:-}" in
  --save)    save ;;
  --restore) restore ;;
  *)
    echo ""
    echo "  Usage: bash token-audit.sh --save | --restore"
    echo ""
    echo "  --save      Snapshot current state to token-audit-state.json,"
    echo "              then enable all MCPs, plugins, and skills."
    echo "              Open Claude Code, /reload-plugins, then /context to measure."
    echo ""
    echo "  --restore   Restore original state from token-audit-state.json."
    echo "              Open Claude Code and /reload-plugins to apply."
    echo ""
    exit 1
    ;;
esac
